"""adds is_verified column to users

Revision ID: 25abebca724f
Revises: 45ef56af5c40
Create Date: 2025-08-18 23:40:06.648403

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "25abebca724f"
down_revision: Union[str, Sequence[str], None] = "45ef56af5c40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_verified",
            sa.Boolean(),
            server_default=sa.text("'false'"),
            nullable=False,
        ),
    )
    op.create_unique_constraint(None, "verification_tokens", ["token_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "verification_tokens", type_="unique")
    op.drop_column("users", "is_verified")
    # ### end Alembic commands ###
