"""refactoring user role and adding cover image to books

Revision ID: 791d70d24c3e
Revises: 49491736007d
Create Date: 2025-08-18 14:53:53.052398

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "791d70d24c3e"
down_revision: Union[str, Sequence[str], None] = "49491736007d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("book_cover_image", sa.String(), nullable=True))
    op.create_unique_constraint(None, "books", ["id"])
    op.alter_column(
        "users",
        "role",
        existing_type=postgresql.ENUM("admin", "user", name="user_roles"),
        type_=sa.String(length=20),
        existing_nullable=False,
    )
    op.create_unique_constraint(None, "users", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column(
        "users",
        "role",
        existing_type=sa.String(length=20),
        type_=postgresql.ENUM("admin", "user", name="user_roles"),
        existing_nullable=False,
    )
    op.drop_constraint(None, "books", type_="unique")
    op.drop_column("books", "book_cover_image")
    # ### end Alembic commands ###
