"""changed token_hash column name to token only in  verification_tokens

Revision ID: b88169abd2e5
Revises: c42fd579ecf6
Create Date: 2025-08-19 10:26:59.117847

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b88169abd2e5"
down_revision: Union[str, Sequence[str], None] = "c42fd579ecf6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "verification_tokens", sa.Column("token", sa.String(), nullable=False)
    )
    op.drop_column("verification_tokens", "token_hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "verification_tokens",
        sa.Column("token_hash", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("verification_tokens", "token")
    # ### end Alembic commands ###
